### PR TITLE
Recognizing old and new connection details class name

### PR DESCRIPTION
**Pull request by schuemie**
In preparation for the new DatabaseConnector release. Hopefully this can be turned into a quick patch release, so DatabaseConnector 6.0.0 can be released.

### CODE REVIEW

**Review by fdefalco — APPROVED** [review]

**Comment by schuemie** [comment]
Could you also increase the package version number and regenerate the documentation? (I didn't want to presume)

**Comment by fdefalco** [comment]
@schuemie Ok, I think the develop branch now has all of what you are looking for, please confirm.  If you agree I'll merge develop to main and tag a formal release of 2.0.

**Comment by schuemie** [comment]
Well, that would make it a major release instead of just a patch release. If I understand correctly, the major release includes major changes to Eunomia. Since many HADES packages depend on Eunomia for unit testing, I wouldn't feel comfortable releasing *that* until we do a full check of all reverse dependencies (which is what I did for DatabaseConnector 6.0.0 as you can see [here](https://github.com/OHDSI/DatabaseConnector/blob/develop/extras/PackageMaintenance.R#L116-L125), which is why I knew we had to make these minor changes to Eunomia's unit test).

So my preference would be for a patch release (1.0.3) now, and after a full reverse dependency check a major release (2.0.0) later.

Also note that in the develop branch the version is '2.0', whereas HADES packages should have 3-digit version numbers ('2.0.0').

**Comment by fdefalco** [comment]
That's true.  Our goal is to publish the major release since we've completely changed Eunomia to now facilitating downloads of sample data sets as opposed to the previous inclusion of the data set within the package itself.  I'll review your approach for a full reverse dependency check and update the version number to include a 3-digit version.  I'll revisit this thread once that is complete before publishing the release.

**Pull request merged**
